# This is a basic workflow to help you get started with Actions

name: Get ClassIcons

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 3 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Set Current Date
        run: echo "currentdate=$(date '+%Y-%m-%d') >> $GITHUB_ENV
        
      - name: wget file
        uses: wei/wget@v1
        with: #studio-icons/ClassImages/ClassImages.png
          args: -O "$currentdate test.png" https://raw.githubusercontent.com/MaximumADHD/Roblox-Client-Tracker/roblox/textures/ClassImages.PNG
      
      - uses: stefanzweifel/git-auto-commit-action@v4
      
