name: Get ClassIcons

on:
  schedule:
  - cron: "0 8 * * *"

  workflow_dispatch:
jobs:
  retrieve:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Current Date
        run: echo "currentdate=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
      
      - name: wget file
        uses: wei/wget@v1
        with: 
          args: https://raw.githubusercontent.com/MaximumADHD/Roblox-Client-Tracker/roblox/textures/ClassImages.PNG
        
      - name: Rename and Move file
        run: mv ClassImages.PNG "ClassImages/$currentdate ClassImages.png"
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
           commit_message: ClassIcons Update
